name: CalculatorChat
main: me.andrestube.calculatorchat.CalculatorChat
api-version: 1.16.5
version: 0.0.4
commands:
  calculatorchat:
    description: CalculatorChat main command
    usage: /calculatorchat <reload|toggle>
    aliases:
      - cc
      - calculator